### ISSUE TITLE
Wrong detection

### ISSUE THREAD

**Issue by yurganov** [vitali-fedulov/images#1]
Hello.

I am trying to compare images with your tool and it works good, except some files.

To reproduce try to compare this image with itself:

https://play-lh.googleusercontent.com/aanOd9yhae5dQXgjwB6XJsGAmGrnkYqiGXNkwtclMuZetDDFkPneG8zOVVAUBhXjMhQ=s512

Your tool will say that it is not similar images.

But your online demo works good with this examples.

Can you help, please?

**Comment by vitali-fedulov** [comment]
Hello,

Thanks for using the package. Could you try to encode the file as a high quality jpeg or gif, and see what happens? It could be an encoding problem of the input file. Please let me know if it worked.

**Comment by yurganov** [comment]
Yes, converting to JPEG helps sometime.

But for example, this image 

https://play-lh.googleusercontent.com/XY26ZKTyBJoHFLZVvOb5E0OAr9rgLBnxDhyR3UDVltYI8riZGjSHzt6H4eQCVDMpV4Q

after converting to JPEG (attaching) and compared to itself gives false result

![1](https://user-images.githubusercontent.com/3879335/91747947-cbe4a500-ebc7-11ea-96e9-278e3d2815a0.jpg)

**Comment by vitali-fedulov** [comment]
Indeed, there was a bug. Thank you for reporting it!

Fixed it: https://github.com/vitali-fedulov/images/commit/8a90db96a358dbb8e1c62d3ac8c952673b9a3a0e

Please let us know if this change has addressed your case.

_I am going to release a major algorithm change within a week or two. It will likely make this bug irrelevant, as the deeper issue is actually related to normalization._
