### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by 89z** [vitali-fedulov/images#5]
Thank you for recent changes - seems only one more

since go.mod was updated after the last tag, documentation thinks no stable version is available:

https://pkg.go.dev/github.com/vitali-fedulov/images/v2

so to fix, all you have to do is just make a new tag, maybe `v2.0.3`

**Comment by vitali-fedulov** [comment]
Strange, it still shows (x) Stable version.

**Comment by 89z** [comment]
yeah, its because `go.mod` was changed after the last tag

**Comment by 89z** [comment]
never mind - its fixed now!

https://pkg.go.dev/github.com/vitali-fedulov/images/v2
